name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Pre-deploy
      run: npm run predeploy

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "ankushkumar7906@gmail.com"
        git config --global user.name "ankushhkumar"
        npm run deploy

