name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure this is the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Ensure this is the latest version
        with:
          node-version: '20'  # Explicitly specify Node.js version 20

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          CI: false  # Prevent warnings from being treated as errors
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

